// export const validationErrors = {
// 	EMAIL: 'EMAIL',
// 	PASSWORD_CONFIRMATION: 'PASSWORD_CONFIRMATION',
// 	PASSWORD_LENGTH: 'PASSWORD_LENGTH',
// 	PASSWORD_LETTER_SIZE: 'PASSWORD_LETTER_SIZE',
// 	PASSWORD_SPECIAL_CHARACTERS: 'PASSWORD_SPECIAL_CHARACTERS',
// 	PASSWORD_DIGIT: 'PASSWORD_DIGIT'
// }